### ISSUE TITLE
Can I use this action for reStructuredText?

### ISSUE THREAD

**Issue by jd41** [vale-cli/vale-action#16]
Is this possible? Running something like the default workflow file only seems to process md files in the project I am looking at.

**Comment by jdkato** [comment]
Yes, this is determined by your `.vale.ini` configuration. The README example (below) uses Markdown, but you're free to configured it as you please.

```ini
StylesPath = .github/styles
MinAlertLevel = suggestion

# Change this to (e.g.) *.rst
[*.md]
BasedOnStyles = Vale
```

**Comment by jd41** [comment]
Thanks!
