### ISSUE TITLE
How to download all generated annotations at once?

### ISSUE THREAD

**Issue by jd41** [vale-cli/vale-action#17]
I am checking out this linter for the nest-simulator documentation, but with the default configuration file, I get a lot of issues that should be ignored (apparently, mainly words that are not in the dictionary but were intended to be used that way). I want to understand/search through some log of issues. How can I download a log file that contains all issues found?

**Comment by jdkato** [comment]
This can be done through the GitHub UI:

![screely-1597174253621](https://user-images.githubusercontent.com/8785025/89940570-8d625880-dbce-11ea-8742-ab85025179e7.png)
