### ISSUE TITLE
Docs for GITHUB_TOKEN

### ISSUE THREAD

**Issue by garethahealy** [vale-cli/vale-action#18]
Are there any docs for what `GITHUB_TOKEN` expects? I tried to use a token with `repo` access but that failed with:

```
You must authenticate via a GitHub App.
```

Any pointers would be helpful.

**Comment by jdkato** [comment]
You shouldn't have to provide the token yourself; copying the example from the docs should be all you need as [`GITHUB_TOKEN`](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret) is built in.
