### ISSUE TITLE
Update vale

### ISSUE THREAD

**Issue by makew0rld** [vale-cli/vale-action#20]
This action only uses Vale v2.2.0, but v2.3.1 is out. Would it be possible to update Vale, so that new features like vocab can be used? This would also require updating the `jdkato/vale` docker container.

**Comment by makew0rld** [comment]
Alright, I did this in [my fork](https://github.com/makeworld-the-better-one/vale-action). Vale is working, but other styles are not for some reason. @jdkato if you have any insight I'd appreciate it.

**Comment by makew0rld** [comment]
How does this program install styles?! It seems that it uses `vale install`, but source code for that command does literally nothing, even for Vale 2.2.0 like this repo uses.

**Comment by jdkato** [comment]
I'm currently working on a release that will expose the Vale version as a configuration option, which I think will offer a better, more consistent experience. This should be ready within a few days.

**Comment by makew0rld** [comment]
This doesn't answer my second question, how does this action install styles? In my fork I just resorted to using `wget` and `unzip`.
