### ISSUE TITLE
Option to only annotate on touched lines

### ISSUE THREAD

**Issue by pierrebeitz** [vale-cli/vale-action#21]
Hi @jdkato and big kudos for the great software you bring to the world!

I recently added this vale-action to an existing repository with hundreds of existing markdown files. To not have this action check all of the repository, we use the `trilom/file-changes-action` as suggested in the readme, along with some custom code that filters those for files ending in `.md` (i now wonder if there's an easier way to have vale ignore the other files 🤔).
Whenever someone changes a line in an existing file, `vale-action` currently produces annotations for the whole file, which gives some members of our organization the feeling that their PR is cluttered and/or hard to review. 

i think that's due to
1. us just starting to use vale and thus not having a configuration that generates as few and meaningful annotations as it could
2. folks not being used to the suggestions that are made by vale (so sometimes the style of writing might actually need to change to generate fewer annotation)
3. github not providing a single button to toggle all annotations for a whole PR

in addition some folks try to make "suggestions" (in the github-sense) to those annotations, which you can only do for changed lines and 3 lines around. they're confused that you can't click the suggest-button outside such a chunk: 

<img width="1211" alt="dcos-docs-site 2020-08-25 11-37-08" src="https://user-images.githubusercontent.com/300861/91158741-6411f400-e6c7-11ea-9086-30b59ffb3c09.png">

now i'm under the impression that only annotating lines that actually changed on a PR might be highly beneficial in our use case. in case you think so too, i wondered whether you would consider having this kind of functionality within `vale-action` or whether you see a way to have this without altering `vale-action`.

In case you also feel a change in `vale-action` would be needed and you'd be willing to have the additional complexity in here, i'd love to contribute that with your guidance.

What do you think?

**Comment by jdkato** [comment]
Hi, thanks for the kind words.

> ... along with some custom code that filters those for files ending in .md (i now wonder if there's an easier way to have vale ignore the other files 🤔).

If you only want Vale to lint Markdown files, you can use a config file along the files of this:

```ini
StylesPath = .github/styles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = Vale
```
This will effectively "ignore" other files since there are no rules enabled for them.

---

Regarding linting only *changed lines*, I'm definitely open to the idea.

There's currently no support for this in Vale itself and it would very likely be non-trivial to implement. However, a good starting point might to offer this functionality only in the action for now:

1. Lint files as usual (all lines);

2. Get a list of changed lines for each linted file; and

3. Filter the JSON output for each linted file based on the changed lines prior to creating the annotations.

Thoughts?

**Comment by pierrebeitz** [comment]
Hi @jdkato, thanks for your reply and sorry for not communicating that i'd be on vacation for quite a bit.

> This will effectively "ignore" other files since there are no rules enabled for them.

🤦 yeah! that's totally obvious now. thanks!

> Filter the JSON output for each linted file based on the changed lines prior to creating the annotations

I was thinking of exactly the same approach. i'll provide a PR once i get to my nice-to-have-list again, which will likely not be in the next 2 weeks.

**Comment by pierrebeitz** [comment]
Hej @jdkato, 

any thoughts on what the API should look like with this feature?

my naive approach would be to just add something like `onlyAnnotateModifiedLines: boolean = false`, as to not break the API. I chose a boolean as i can currently not think of any other value that might make sense here in the future. Can you think of one? (e.g. `annotateLines: "modified" | "all" | ???`)

> Get a list of changed lines for each linted file

do you have an idea of how to elegantly obtain this? 
hacking a node-script that computes the right things is the easy part here. i'm rather unsure about whether that should be an action of its own or whether we incorporate git-usage into the vale-action. do you know whether we we can do this at all, as it's running inside a container?

-----------

if you don't have time to dig into the details, just let me know. feedback regarding the API would be nice in any case though. thanks!

**Comment by jdkato** [comment]
API-wise, I think `onlyAnnotateModifiedLines` is fine. A use case beyond "modified" or "all" isn't immediately obvious to me either.

> do you have an idea of how to elegantly obtain this?

To me, Git feels like the most natural solution but I don't have strong opinions on the matter. I also don't think the container environment should be much of an issue; if you need access to a dependency, you can update the [Dockerfile](https://github.com/errata-ai/vale-action/blob/master/Dockerfile).

**Comment by pierrebeitz** [comment]
Here's a first version: https://github.com/errata-ai/vale-action/pull/23. Please let me know what you think!
