### ISSUE TITLE
 Can Action support spelling checks

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale-action#3]
I noticed that you disabled spelling checks in your example, and so far when I've tested, actions with spelling checks defined seem to fail silently, so as far as you know, are they not currently possible, and what would be needed to make them possible?

**Comment by jdkato** [comment]
They are possible, as far as I know. In fact, I'm using `Vale.Spelling` in this very repo: it's only disabled in the Gist (which I'm assuming is the example in question) to illustrate the ability to locally override a remote config (see https://github.com/errata-ai/vale-action/blob/master/.vale.ini).

Can you share the repo you're testing with?

**Comment by ChrisChinchilla** [comment]
@jdkato Hmm, odd, I wish actions were easier to debug :(
