### ISSUE TITLE
Encounter affix key error beyond `v1.3.0`

### ISSUE THREAD

**Issue by paddyroddy** [vale-cli/vale-action#38]
Related to this issue https://github.com/errata-ai/vale/issues/328.

I recently upgraded the CI from `v1.3.0` to `v1.4.1` (and tested `v.1.4.0` too) and encounter this error. This does not happen with `v1.3.0`.
![image](https://user-images.githubusercontent.com/15052188/118518166-c4eacc00-b72f-11eb-8308-141451b363dc.png)

This is recently got fixed in `vale` and does not occur for me locally `vale version 2.10.3`.

**Comment by jdkato** [comment]
Thanks for the report -- I'll publish a new version that uses the latest Vale release soon.
