### ISSUE TITLE
Does this action support DITA files?

### ISSUE THREAD

**Issue by jiewang2** [vale-cli/vale-action#51]
Got this error when including .dita files in the action:
```
Error: {
11
  "Code": "E100",
12
  "Text": "E100 [lintDITA] Runtime error\n\ndita not found\n\nExecution stopped with code 1."
13
}
```

**Comment by jdkato** [comment]
No, not currently.

The required deps aren't included `jdkato/vale` because they make the size ~7x as large. I'd like to make this opt-in eventually, though.

**Comment by jdkato** [comment]
DITA is supported now in the new `@reviewdog` version.
