### ISSUE TITLE
GitHub action fails if remotely-hosted `config` is used

### ISSUE THREAD

**Issue by jouni** [vale-cli/vale-action#55]
If I define [remotely-hosted `config`](https://github.com/errata-ai/vale-action#config) for the action, it fails with the following error, implying that the style rules are not found:

```
Error: {
  "Code": "E100",
  "Text": "E100 [NewE201] Runtime error\n\nopen Vaadin/Abbr.yml: no such file or directory\n\nExecution stopped with code 1."
}
```

This used to work, but started to fail consistently ~2 weeks ago.

Here’s an example PR, where it first works without the `config` ([commit #1](https://github.com/vaadin/docs/pull/1115/commits/41fe0bb7b21061aedd73a6191a7af560ba94baa8)), but when it’s added, it starts failing ([commit #2](https://github.com/vaadin/docs/pull/1115/commits/7baaa0d12a1eec8f4ca8a409857766d62a0df714)).

**Comment by jdkato** [comment]
This should be fixed now with the upgrade to v2.15.2.

**Comment by jouni** [comment]
Olay, great! So just wait and it should resolve automatically, or should I do something to update?

**Comment by jouni** [comment]
Ah, now I saw the new release 👍

**Comment by jdkato** [comment]
If you're using `@master`, it should update automatically. If you're using a pinned version, you'll need to update your workflow file.

**Comment by jouni** [comment]
Yeah, we are using `@master`. Looks like the actions are running fine again. Thanks!
