### ISSUE TITLE
Provide a new release to use the vale v2.15.3 or later

### ISSUE THREAD

**Issue by TibsAtWork** [vale-cli/vale-action#61]
The current release of vale-action, v1.5.0, provides vale v2.15.2

vale v2.15.5 now exists.
I in particular would like vale v2.15.3 but I assume it would be sensible to go for the latest release.

**Comment by TibsAtWork** [comment]
If it would help if I made a PR, I can do so - I do not know the custom for this repository.

**Comment by jdkato** [comment]
The latest release is now available on `@master`.

**Comment by TibsAtWork** [comment]
Many thanks
