### ISSUE TITLE
How to only run Vale on modified files?

### ISSUE THREAD

**Issue by mattbrailsford** [vale-cli/vale-action#8]
Currently when using the Vale GitHub action the example configuration runs Vale across all files in the repository but do you have an example configuration where Vale is only run against the files that have been modified in the commit / PR?

**Comment by jdkato** [comment]
No, there's currently no built-in support for specifying what files to lint beyond the [repo path](https://github.com/errata-ai/vale-action#files-default-all) option.

This is something that I'd like to implement in the future (probably using [`file-changes-action`](https://github.com/marketplace/actions/file-changes-action)).

**Comment by mattbrailsford** [comment]
@jdkato cool. Looking at that action, do you think there are actually any changes that are needed? Or could the output variables be fed straight into the files option in the main.yml workflow file?

**Comment by jdkato** [comment]
Yes, the changes should be minimal but the output of that action does need to processed somewhat:

https://github.com/errata-ai/vale-action/blob/de680a81bc6fb592f52f70c5abdc950dd8cb6a2b/src/input.ts#L87-L97

**Comment by mattbrailsford** [comment]
Ahhh, cool. 

Struggling to tell from the docs I can find, but does the Vale command line support multiple file paths? Or just a single dir/file path? 

Would this then need to run once per file? Or would you try and generate one big glob pattern to filter on? Or something else? (Wondering if it’s something I could try to help on)

**Comment by jdkato** [comment]
Yes, you can pass multiple arguments to Vale: `vale file1 dir1 file2`.

**Comment by ChrisChinchilla** [comment]
> No, there's currently no built-in support for specifying what files to lint beyond the [repo path](https://github.com/errata-ai/vale-action#files-default-all) option.
> 
> This is something that I'd like to implement in the future (probably using [`file-changes-action`](https://github.com/marketplace/actions/file-changes-action)).

Ah, I didn't realise that, might explain some of my issues with the action. Should have a little time to look more at tweaks and usage instructions for more advanced setups soon, when I get back to some repo and Vale work.

**Comment by nkuehn** [comment]
> Yes, you can pass multiple arguments to Vale: `vale file1 dir1 file2`.

Would be awesome to be able to have the action pass through the "files" argument directly to vale without a strict check whether the path exists to leverage the globbing expressivity of the vale CLI.  

To not break the existing API, how about allowing to pass an array to "files" that is then interpreted as a list of the globs that the vale CLI accepts?  A sanity check that no random config flag is passed could be done inversely then and check that none of the entries starts with a dash after trimming it.

**Comment by jdkato** [comment]
This is available now in v1.3.0.

@nkuehn: Your request, assuming I understood correctly, is also now supported.

See the new description for [`files`](https://github.com/errata-ai/vale-action#files-default-all) for more information.
